/**
 * HTML formatter — semantic, accessible markup with CSS class hooks.
 */

import type { AstrologyEvent, FormatterOptions } from "./types.js";
import { PLANET_SYMBOLS, ASPECT_SYMBOLS, SIGN_SYMBOLS, PLANET_NAMES, SIGN_NAMES } from "./symbols.js";

function esc(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function formatEventRow(event: AstrologyEvent): string {
  const date = new Date(event.exactAtUtc);
  const time = `${String(date.getUTCHours()).padStart(2, "0")}:${String(date.getUTCMinutes()).padStart(2, "0")} UTC`;
  const dateStr = date.toISOString().slice(0, 10);

  const bodies = event.bodies
    .map((b) => {
      const sym = PLANET_SYMBOLS[b as keyof typeof PLANET_SYMBOLS] ?? "";
      const name = PLANET_NAMES[b as keyof typeof PLANET_NAMES] ?? b;
      return `<span class="ae-planet" title="${esc(name)}">${sym}</span>`;
    })
    .join(" ");

  const signSym = SIGN_SYMBOLS[event.sign as keyof typeof SIGN_SYMBOLS] ?? "";
  const signName = SIGN_NAMES[event.sign as keyof typeof SIGN_NAMES] ?? event.sign;
  const degree = `${Math.floor(event.degree)}°${Math.floor((event.degree % 1) * 60)}'`;

  let detail = "";
  if (event.aspect) {
    const aspectSym = ASPECT_SYMBOLS[event.aspect.type as keyof typeof ASPECT_SYMBOLS] ?? "";
    detail = `<span class="ae-aspect">${aspectSym} ${event.aspect.orb.toFixed(1)}° ${event.aspect.phase}</span>`;
  } else if (event.type === "ingress") {
    detail = `<span class="ae-direction">→</span>`;
  } else if (event.station) {
    detail = `<span class="ae-station">${event.station === "retrograde" ? "℞" : "D"}</span>`;
  } else if (event.lunation) {
    detail = `<span class="ae-lunation">${event.lunation.replace(/_/g, " ")}</span>`;
  }

  const sigClass = `ae-sig-${event.significance}`;

  return `    <tr class="ae-event ae-type-${event.type} ae-stream-${event.stream} ${sigClass}">
      <td class="ae-date">${dateStr}</td>
      <td class="ae-time">${time}</td>
      <td class="ae-bodies">${bodies}</td>
      <td class="ae-aspect-detail">${detail}</td>
      <td class="ae-sign"><span class="ae-sign-symbol" title="${esc(signName)}">${signSym}</span> ${esc(signName)}</td>
      <td class="ae-degree">${degree}</td>
      <td class="ae-significance"><span class="ae-badge">${event.significance}</span></td>
    </tr>`;
}

/**
 * Format events as semantic HTML.
 */
export function formatAsHTML(
  events: readonly AstrologyEvent[],
  options?: FormatterOptions,
): string {
  const title = options?.title ?? "Astro Engine — Transit Report";
  const generated = new Date().toISOString();

  const rows = events.map(formatEventRow).join("\n");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${esc(title)}</title>
  <style>
    .ae-table { width: 100%; border-collapse: collapse; font-family: system-ui, sans-serif; font-size: 14px; }
    .ae-table th { text-align: left; padding: 8px 12px; border-bottom: 2px solid #333; color: #888; font-weight: 500; }
    .ae-table td { padding: 8px 12px; border-bottom: 1px solid #1a1a1a; }
    .ae-event:hover { background: rgba(124, 58, 237, 0.08); }
    .ae-planet { font-size: 16px; }
    .ae-aspect { color: #a78bfa; }
    .ae-station { color: #f59e0b; font-weight: 600; }
    .ae-lunation { color: #60a5fa; text-transform: capitalize; }
    .ae-direction { color: #6b7280; }
    .ae-sign-symbol { font-size: 16px; }
    .ae-badge { font-size: 11px; padding: 2px 6px; border-radius: 4px; text-transform: uppercase; }
    .ae-sig-major .ae-badge { background: #7c3aed22; color: #a78bfa; }
    .ae-sig-notable .ae-badge { background: #3b82f622; color: #60a5fa; }
    .ae-sig-daily .ae-badge { background: #6b728022; color: #9ca3af; }
    .ae-meta { color: #6b7280; font-size: 12px; margin-bottom: 16px; }
  </style>
</head>
<body>
  <header>
    <h1>${esc(title)}</h1>
    <p class="ae-meta">Generated: ${generated} · ${events.length} events</p>
  </header>
  <table class="ae-table" role="table" aria-label="Astrology transit events">
    <thead>
      <tr>
        <th scope="col">Date</th>
        <th scope="col">Time</th>
        <th scope="col">Bodies</th>
        <th scope="col">Aspect</th>
        <th scope="col">Sign</th>
        <th scope="col">Degree</th>
        <th scope="col">Level</th>
      </tr>
    </thead>
    <tbody>
${rows}
    </tbody>
  </table>
  <footer class="ae-meta">
    <p>Generated by <a href="https://github.com/nivaaz/astro-engine">Astro Engine</a> · Sukara Technology</p>
  </footer>
</body>
</html>`;
}
